[theme]
primaryColor = "#10a37f"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f7f8"
textColor = "#343541"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false